### ISSUE TITLE
Error: $injector:modulerr Module Error

### ISSUE THREAD

**Issue by ecSpl01t** [m-e-conroy/angular-dialog-service#177]
Hi,
When I just to add module in my app, I got error $injector:modulerr

```
require('angular-dialog-service')

angular.module("altmeApp", ['ui.bootstrap', ngRoute, ngCookie, 'btford.socket-io', 'route-segment', 'view-segment', 'toggle-switch', 'dialogs.main'])
```

```
Failed to instantiate module altmeApp due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=d...)
    at Error (native)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:6:412
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:40:134
    at q (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:7:355)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:39:222)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:39:391
    at q (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:7:355)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:39:222)
    at bb (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:43:246)
    at c (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:21:19
```

**Comment by niemyjski** [comment]
Did you reference the js files in your index.html file / module loader?

**Comment by fikipollo** [comment]
Same problem here :P 
Using  dialogs.min.js and  dialogs.min.css from _dist_ folder and AngularJS 1.5.5

``
  var app = angular.module('workflows.directives.workflow-run', [
    'ui.bootstrap',
    'dialogs.main'
  ]);
``

``
angular.js:38Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=b3galaxyApp&p1=Erro…oogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.5%2Fangular.min.js%3A21%3A19)
``

Thanks!

**Comment by fikipollo** [comment]
Actually it looks like the problem is related with the version of  ui-bootstrap.
Only works with versions of ui-bootstrap < 1.0 
- tested using 0.9.0 -> works
- tested using 1.0.0 and later -> error
 
hope that helps!

**Comment by joshsinger** [comment]
I can confirm the same issue. This is a problem for me as I would like to update to later versions of ui-bootstrap.

**Comment by Maano412** [comment]
I dont know how to solve this error

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.32/$injector/modulerr?p0=contactsMgr&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.32%2F%24injector%2Fnomod%3Fp0%3DcontactsMgr%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A6%3A450%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A20%3A494%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A21%3A502%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A33%3A267%0A%20%20%20%20at%20r%20(file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A7%3A290)%0A%20%20%20%20at%20e%20(file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A33%3A207)%0A%20%20%20%20at%20dc%20(file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A36%3A309)%0A%20%20%20%20at%20c%20(file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A18%3A170)%0A%20%20%20%20at%20cc%20(file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A18%3A387)%0A%20%20%20%20at%20Xc%20(file%3A%2F%2F%2FC%3A%2FUsers%2Fmaano%2FDesktop%2FAIE2%2Fangular%2Fassets%2Fjs%2Fangular.min.js%3A17%3A415)
    at angular.min.js:6:450
    at angular.min.js:34:97
    at r (angular.min.js:7:290)
    at e (angular.min.js:33:207)
    at dc (angular.min.js:36:309)
    at c (angular.min.js:18:170)
    at cc (angular.min.js:18:387)
    at Xc (angular.min.js:17:415)
    at HTMLDocument.<anonymous> (angular.min.js:217:78)
    at e (jquery.min.js:2:30158)
